/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_Platri_WRAP_H_
#define SWIG_Platri_WRAP_H_

namespace Swig {
  class Director;
}


class SwigDirector_Application : public Application, public Swig::Director {

public:
    SwigDirector_Application(VALUE self);
    virtual Object *createObject(TuioObject *tobj);
    virtual Cursor *createCursor(TuioCursor *tcur);
    virtual void display();
    virtual void start();
};


class SwigDirector_Object : public Object, public Swig::Director {

public:
    SwigDirector_Object(VALUE self, TuioObject *tobj);
    virtual void display();
};


#endif
